### ISSUE TITLE
Allow de/serialization of Maps 

### ISSUE THREAD

**Issue by thosakwe** [agilord/owl#1]
I'm willing to contribute to bringing this feature around, just let me know if I have the green light.

See, I'm using `owl` to build an [OpenAPI specification library](https://github.com/thosakwe/openapi/blob/master/lib/src/schemas.dart), but the specification declares several fields that can best be expressed as Dart Maps. Example:

```dart
Map<String, SecurityScheme> securityDefinitions;
```

I've wound up using `@Transient()` or `@JsonField(native: true)` and writing manual code in a `fromMap` factory constructor or the `toJson` method. This is very tedious, and can indeed be automated. Something like:

```dart
// parse(map)
object.securityDefinitions = map['securityDefinitions']?.keys?.fold(
  {},
  (out, k) =>
    out..[k.toString()] = SecuritySchemeMapper.parse(map['securityDefinitions'][k]));

// map(object)
return (new _owl_json.MapBuilder(ordered: false)
          ..put('securityDefinitions', securityDefinitions.keys.fold(
            {},
            (out, k) =>
                out..[k] = SecuritySchemeMapper.map(securityDefinitions[k]))))
        .toMap();
```

For conveniency's sake, it might be a good idea to switch to using `package:code_builder`. This would also make it possible to generate something for this field:

```dart
Map<String, Map<String, Operation>> paths;
```

If you feel like this would be a good addition to `owl`, please let me know, and I will get right to it.

**Comment by isoos** [comment]
Apologies for the late reply, I was offline on the weekend. This looks a great addition, I'd appreciate the contribution.

Please make sure that you add the field's pattern to the example (it acts as a 'smoke'-test), or if you have a good idea how this should be properly tested, add a simple test case.

**Comment by thosakwe** [comment]
@isoos Cool. I do think that it will be necessary for me to convert the package to using `code_builder` first. I'll make a fork (new branch) for that, and then if you're good with that, then I can continue to add the feature I mentioned in this issue (maps).

**Comment by isoos** [comment]
@thosakwe Does `code_builder` add you any analysis capabilities that are required? If not, I would be cautious with a rewrite, and I'd suggest to do it one step at a time e.g. if you want to implement the new part with `code_builder` that is fine, but I see little use-case to rewrite the rest.

**Comment by rinukkusu** [comment]
Hi @thosakwe - any progress on this? Just ran into needing a `Map` in a specific place, too, since it's an object with variable keys/values :(

**Comment by thosakwe** [comment]
@rinukkusu No progress right now, really busy with lots of other things. :( Not sure when I'll have a change to get to this, sorry.

**Comment by isoos** [comment]
@rinukkusu: I've got a similar requirement not long ago, but I was able to re-design the interface to List of objects. Are you in a pressing need for this?

**Comment by rinukkusu** [comment]
@isoos No, `List<dynamic>` is fine too for now.

**Comment by isoos** [comment]
FYI: I think [`package:json_serializable`](https://pub.dartlang.org/packages/json_serializable) has advanced enough in the past year that I can't really think of significant advances that justify a separate library. Instead, I'll focus first on the database-related codes, and then on the http-services. (There will be some breaking changes coming up, I have a separate private branch of the code that I'm using for a while).
